// <auto-generated />
namespace SampleMVC4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class domainvar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(domainvar));
        
        string IMigrationMetadata.Id
        {
            get { return "201308012148449_domain-var"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
