//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeNode
    {
        public TreeNode()
        {
            this.ParentNode = new HashSet<TreeNode>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TreeNodeId { get; set; }
    
        public virtual ICollection<TreeNode> ParentNode { get; set; }
        public virtual TreeNode ChildNodes { get; set; }
    }
}
