//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeListValues
    {
        public CodeListValues()
        {
            this.SpecCodeListValues = new HashSet<SpecCodeListValues>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public int CodeListId { get; set; }
    
        public virtual CodeList CodeList { get; set; }
        public virtual ICollection<SpecCodeListValues> SpecCodeListValues { get; set; }
    }
}
