//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domain
    {
        public Domain()
        {
            this.Variables = new HashSet<Variable>();
            this.DerivedDomains = new HashSet<Domain>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DomainClass Class { get; set; }
        public string StructureDescription { get; set; }
        public string CommentText { get; set; }
        public bool IsStandard { get; set; }
        public bool IsTemplate { get; set; }
        public Nullable<int> StudyId { get; set; }
        public Nullable<int> DomainId { get; set; }
        public Nullable<int> MetaDataVersionId { get; set; }
    
        public virtual ICollection<Variable> Variables { get; set; }
        public virtual Study Study { get; set; }
        public virtual ICollection<Domain> DerivedDomains { get; set; }
        public virtual Domain SourceDomain { get; set; }
        public virtual MetaDataVersion MetaDataVersion { get; set; }
    }
}
