//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    
    public enum DomainClass : int
    {
        EVENTS = 1,
        INTERVENSIONS = 2,
        FINDINGS = 3,
        SPECIAL_PURPOSE_DOMAINS = 4
    }
}
