//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    
    public enum Domaintype : int
    {
        EVENTS = 0,
        INTERVENSIONS = 1,
        FINDINGS = 2,
        SPECIAL_PURPOSE_DOMAINS = 3
    }
}
