//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainVariable
    {
        public DomainVariable()
        {
            this.SpecDomainVariables = new HashSet<SpecDomainVariable>();
        }
    
        public int Id { get; set; }
        public string Required { get; set; }
        public bool HasCodeList { get; set; }
        public int DomainId { get; set; }
        public int VariableId { get; set; }
    
        public virtual Domain Domain { get; set; }
        public virtual Variable Variable { get; set; }
        public virtual ICollection<SpecDomainVariable> SpecDomainVariables { get; set; }
    }
}
