//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDR
    {
        public MDR()
        {
            this.StandardDomains = new HashSet<StandardDomain>();
            this.StandardVariables = new HashSet<StandardVariable>();
            this.StandardCodeLists = new HashSet<StandardCodeList>();
        }
    
        public int Id { get; set; }
        public string Version { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<StandardDomain> StandardDomains { get; set; }
        public virtual ICollection<StandardVariable> StandardVariables { get; set; }
        public virtual ICollection<StandardCodeList> StandardCodeLists { get; set; }
    }
}
