//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public Specification()
        {
            this.SpecDomains = new HashSet<SpecDomain>();
            this.SpecDomainVariables = new HashSet<SpecDomainVariable>();
            this.SpecCodeListValues = new HashSet<SpecCodeListValues>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int StudyId { get; set; }
    
        public virtual Study Study { get; set; }
        public virtual ICollection<SpecDomain> SpecDomains { get; set; }
        public virtual ICollection<SpecDomainVariable> SpecDomainVariables { get; set; }
        public virtual ICollection<SpecCodeListValues> SpecCodeListValues { get; set; }
    }
}
