//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecCodeListValues
    {
        public int Id { get; set; }
        public int CodeListValuesId { get; set; }
        public int SpecificationId { get; set; }
    
        public virtual CodeListValues CodeListValue { get; set; }
        public virtual Specification Specification { get; set; }
    }
}
