//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study
    {
        public Study()
        {
            this.Domains = new HashSet<Domain>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CompoundId { get; set; }
    
        public virtual Compound Compound { get; set; }
        public virtual ICollection<Domain> Domains { get; set; }
    }
}
