//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    
    public enum VariableRole : int
    {
        Identifier = 1,
        Record_Qualifier = 2,
        Result_Qualifier = 3,
        Synonym_Qualifier = 4,
        Timing = 5,
        Topic = 6,
        Variable_Qualifier = 7
    }
}
