//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Variable
    {
        public Variable()
        {
            this.DomainVariables = new HashSet<DomainVariable>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DomainVariablePattern { get; set; }
    
        public virtual ICollection<DomainVariable> DomainVariables { get; set; }
    }
}
