//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    
    public enum VariableOrgin : int
    {
        Assigned = 1,
        CRF = 2,
        Derived = 3,
        eDT = 4,
        Protocol = 5
    }
}
